version: 2

aliases:
    - &restore_gem_cache
        keys: 
            - v1-gemfile-{{ checksum "Gemfile.lock" }}

    - &save_gem_cache
        name: Saving gem cache
        key: v1-gemfile-{{ checksum "Gemfile.lock" }}
        paths: 
            - ~/data/vendor/bundle
    
    - &bundle_install
        name: Install Gems
        command: bundle install --path=vendor/bundle --jobs=4 --retry=3

defaults: &defaults
  docker: 
    - image: ruby:2.5.1
  working_directory: ~/data

jobs:
  rspec:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *bundle_install
      - save_cache: *save_gem_cache
      - run: bundle exec rspec

  cucumber:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *bundle_install
      - save_cache: *save_gem_cache
      - run: bundle exec cucumber

workflows:
    version: 2
    pr:
        jobs:
            - rspec
            - cucumber